### ISSUE TITLE
tips

### ISSUE THREAD

**Issue by Lunction** [Mas0nShi/jscHookR#3]
Traceback (most recent call last):
  File "/root/Desktop/jscHookR/frida-jsc-hook.py", line 3, in <module>
    from jscHookR2.core import Callback
  File "/root/Desktop/jscHookR/jscHookR2/core.py", line 49, in <module>
    class ReceiveMessage:
  File "/root/Desktop/jscHookR/jscHookR2/core.py", line 91, in ReceiveMessage
    def callback(self) -> CallbackResult | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by Mas0nShi** [comment]
plz use python 3.10+

refer: https://stackoverflow.com/questions/76712720/typeerror-unsupported-operand-types-for-type-and-nonetype

**Comment by Lunction** [comment]
3q
